basePath: /api
definitions:
  request.SearchLink:
    properties:
      email:
        type: string
      number_links:
        type: integer
      url:
        type: string
    type: object
  response.ErrorMessage:
    properties:
      invalid_fields:
        items:
          $ref: '#/definitions/response.InvalidField'
        type: array
      message:
        type: string
      status_code:
        type: integer
    type: object
  response.ID:
    properties:
      id:
        type: string
    type: object
  response.InvalidField:
    properties:
      description:
        type: string
      field_name:
        type: string
    type: object
info:
  contact:
    email: tgazaroli@gmail.com
    name: Thiago gazaroli
  title: Web Crawler Backend API
  version: "1.0"
paths:
  /api/search-link:
    post:
      consumes:
      - application/json
      description: |-
        Ao Prencher os o body da requisição com a url base, email que o usario quer receber os links encontrados e a quantidade de links que deverá ser encontrado
        OBS: Recomendamos  preencher o campo de quantidade de links com até 150, estaremos trabalhando para aumentar exponencialmente esse número
      operationId: Crawler.SearchLinks
      parameters:
      - description: JSON com todos os dados necessários para que seja possivel realizar
          a buscas das urls
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/request.SearchLink'
      produces:
      - application/json
      responses:
        "201":
          description: Requisição realizada com sucesso.
          schema:
            $ref: '#/definitions/response.ID'
        "500":
          description: Ocorreu um erro inesperado. Por favor, contate o suporte.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
        "503":
          description: A base de dados está temporariamente indisponível.
          schema:
            $ref: '#/definitions/response.ErrorMessage'
      summary: Buscador de urls a partir da url enviada
swagger: "2.0"
